### ISSUE TITLE
Update to 1.20.2 >>> newer versions please

### ISSUE THREAD

**Issue by sternschnaube** [CJMinecraft01/ReloadAudioDriverFabric#6]

**Comment by JayJay1989** [comment]
I will update this for minecraft 1.20.x

**Comment by venaminecraft** [comment]
Thank you @JayJay1989 🥳

**Comment by JayJay1989** [comment]
Its uploaded to CurseForge, it takes a while till you can download it

**Comment by venaminecraft** [comment]
Thank you so much again for the fast update!!
